name: Deploy WebSocket App to EKS

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_BACKEND: dhruv789/websocket-server
  DOCKER_IMAGE_FRONTEND: dhruv789/frontend-server
  KUBECONFIG_PATH: "/home/runner/.kube/config"

jobs:
  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend Image
        run: |
          docker build -t $DOCKER_IMAGE_BACKEND backend/
          docker push $DOCKER_IMAGE_BACKEND

      - name: Build & Push Frontend Image
        run: |
          docker build -t $DOCKER_IMAGE_FRONTEND frontend/
          docker push $DOCKER_IMAGE_FRONTEND

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name flytbase-cluster --region eu-west-2
          kubectl version --client

      - name: Deploy to EKS
        run: kubectl apply -f k8s/
